apiVersion: v1
kind: Service
metadata:
  name: order-process-manager
  namespace: microservices-workshop
spec:
  selector:
    app: order-process-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
